### ISSUE TITLE
Arrumar o Footer

### ISSUE THREAD

**Issue by mrlFranchi** [Ryrden/GCMES-Trab#7]
Arrumar o footer

![Imagem Site](https://i.imgur.com/FejBWxh.png)

**Comment by Vasini25** [comment]
Boa Issue, obrigado pela proposta, será corrigido e melhorado.

**Comment by Ryrden** [comment]
Perfeito, eu e o @MatheusOde já começamos

**Comment by Ryrden** [comment]
Resolvemos no PR #9

**Comment by mrlFranchi** [comment]
Era oque eu queria

![Issue resolvida](https://i.imgur.com/F4bizk8.png)
